use std::sync::{Arc, Mutex, MutexGuard};

use image::ExtendedColorType;
use image::ImageEncoder;
use image::codecs::png::PngEncoder;
use zeroize::{Zeroize, Zeroizing};

use crate::commands::{CardView, ImageScan, WorkCard};
use crate::format;
use crate::image_edit::ImageVersions;
use crate::table::TableVersions;

pub const MAX_HISTORY: usize = 20;

/// Derived data (cards, image scans) is kept for the entry being shown and this many entries on
/// either side; further away it is zeroized and worked out again when needed.
const DERIVED_NEAR: usize = 1;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClipboardImage {
    pub width: usize,
    pub height: usize,
    pub rgba: Vec<u8>,
    /// Clipboard pixel size. `width` and `height` can be a smaller preview.
    pub full_width: usize,
    pub full_height: usize,
}

impl ClipboardImage {
    pub fn new(width: usize, height: usize, rgba: Vec<u8>) -> Option<Self> {
        let pixels = width.checked_mul(height)?.checked_mul(4)?;
        if width == 0 || height == 0 || rgba.len() != pixels {
            return None;
        }
        Some(Self {
            width,
            height,
            rgba,
            full_width: width,
            full_height: height,
        })
    }

    #[cfg(not(target_os = "macos"))]
    pub fn from_arboard(data: arboard::ImageData<'_>) -> Option<Self> {
        Self::new(data.width, data.height, data.bytes.into_owned())
    }

    pub fn png_bytes(&self) -> Result<Vec<u8>, String> {
        let mut buf = Vec::new();
        PngEncoder::new(&mut buf)
            .write_image(
                &self.rgba,
                self.width as u32,
                self.height as u32,
                ExtendedColorType::Rgba8,
            )
            .map_err(|e| e.to_string())?;
        Ok(buf)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClipboardView {
    Empty,
    NoText,
    /// Owned clipboard text. Dropping the view overwrites that allocation.
    Text(Zeroizing<String>),
    /// An image is on the clipboard. Pixels are not loaded here.
    Image,
    /// Another app marked the copy private (a password manager's Concealed type, Transient or
    /// AutoGenerated). Its text is not read, cached or recorded.
    Hidden,
    /// Pasteboard privacy is set to Always Deny for Copycraft: nothing is read
    /// ([`crate::paste_access`]).
    Denied,
    /// Pasteboard privacy is Default or Ask: a new copy, not read until the card is shown
    /// ([`crate::paste_access::ReadStrategy::WhenShown`]).
    Pending,
}

impl ClipboardView {
    pub fn from_os() -> Self {
        #[cfg(target_os = "macos")]
        {
            // The menu refreshes several times a second. Reading pixels here
            // decodes a full image every time and stalls the process.
            crate::macos_pasteboard::current_view()
        }
        #[cfg(not(target_os = "macos"))]
        {
            from_os_fallback()
        }
    }

    pub fn text(&self) -> Option<&str> {
        match self {
            Self::Text(text) => Some(text.as_str()),
            Self::Empty
            | Self::NoText
            | Self::Image
            | Self::Hidden
            | Self::Denied
            | Self::Pending => None,
        }
    }

    pub fn is_image(&self) -> bool {
        matches!(self, Self::Image)
    }

    #[cfg_attr(not(test), allow(dead_code))]
    pub fn is_previewable(&self) -> bool {
        matches!(self, Self::Text(_) | Self::Image)
    }

    #[cfg_attr(not(test), allow(dead_code))]
    pub fn type_mark(&self) -> Option<&'static str> {
        match self {
            Self::Text(text) => Some(menu_mark(text.as_str())),
            Self::Image => Some(format::FormatKind::Image.menu_symbol()),
            Self::Empty | Self::NoText | Self::Hidden | Self::Denied | Self::Pending => None,
        }
    }

    #[cfg_attr(not(test), allow(dead_code))]
    pub fn label(&self) -> String {
        match self {
            Self::Empty => "(clipboard is empty)".to_string(),
            Self::NoText => "(clipboard has no text)".to_string(),
            Self::Text(text) => one_line(text.as_str()),
            Self::Image => format::FormatKind::Image.menu_symbol().to_string(),
            Self::Hidden => HIDDEN_CONTENT.to_string(),
            Self::Denied => crate::paste_access::DENIED_NOTE.to_string(),
            Self::Pending => crate::paste_access::PENDING_NOTE.to_string(),
        }
    }
}

/// Image bytes shared by history and the current-item handle.
/// `zeroize` overwrites the one allocation every clone points at.
#[derive(Clone)]
pub struct SecretBytes {
    inner: Arc<Mutex<Zeroizing<Vec<u8>>>>,
}

impl SecretBytes {
    pub fn new(bytes: Vec<u8>) -> Option<Self> {
        if bytes.is_empty() {
            return None;
        }
        Some(Self {
            inner: Arc::new(Mutex::new(Zeroizing::new(bytes))),
        })
    }

    pub fn zeroize(&self) {
        self.lock().zeroize();
    }

    pub fn with<R>(&self, read: impl FnOnce(&[u8]) -> R) -> R {
        read(self.lock().as_slice())
    }

    pub fn same_allocation(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.inner, &other.inner)
    }

    /// Tells this allocation from others while it lives (see [`same_allocation`](Self::same_allocation)).
    pub fn allocation_id(&self) -> usize {
        Arc::as_ptr(&self.inner) as usize
    }

    fn lock(&self) -> MutexGuard<'_, Zeroizing<Vec<u8>>> {
        self.inner.lock().unwrap_or_else(|err| err.into_inner())
    }

    #[cfg(test)]
    fn prefix_is_zero(&self, len: usize) -> bool {
        let guard = self.lock();
        if !guard.is_empty() || guard.capacity() < len {
            return false;
        }
        let ptr = guard.as_ptr();
        // SAFETY: zeroize keeps this allocation and writes zeros across its
        // capacity. `len` is inside that capacity, and `guard` still owns it.
        let wiped = unsafe { std::slice::from_raw_parts(ptr, len) };
        wiped.iter().all(|byte| *byte == 0)
    }
}

/// Never shows the bytes.
impl std::fmt::Debug for SecretBytes {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SecretBytes(..)")
    }
}

impl PartialEq for SecretBytes {
    fn eq(&self, other: &Self) -> bool {
        if self.same_allocation(other) {
            return true;
        }
        let left = self.lock();
        let right = other.lock();
        left.as_slice() == right.as_slice()
    }
}

impl Eq for SecretBytes {}

#[derive(Clone)]
enum HistoryBody {
    Text(Zeroizing<String>),
    Image(SecretBytes),
}

/// One copied item, and what was worked out from it once: its format, and the cards built for
/// it (one per view). Stepping through history shows the same entries again and again, so they
/// are not detected, formatted and laid out anew each time.
/// The cards go with the entry: falling off the end or Wipe drops and zeroizes them with it.
/// Only the entries near the one shown keep them ([`DERIVED_NEAR`]).
#[derive(Clone)]
struct HistoryEntry {
    body: HistoryBody,
    kind: format::FormatKind,
    cards: Vec<(CardView, WorkCard)>,
    /// A picture's info, OCR text, QR payload and data URL, once scanned.
    scan: Option<ImageScan>,
    /// A table's versions (the steps taken on the card), once the card worked on it. Its
    /// frames are derived data like the cards; its steps stay with the entry.
    table: Option<TableVersions>,
    /// A picture's versions (the Image ▾ steps), once the card worked on it. Like a table's,
    /// its pictures are derived data; its steps stay with the entry.
    images: Option<ImageVersions>,
}

impl HistoryEntry {
    fn text(text: String) -> Self {
        let kind = format::detect(&text);
        Self {
            body: HistoryBody::Text(Zeroizing::new(text)),
            kind,
            cards: Vec::new(),
            scan: None,
            table: None,
            images: None,
        }
    }

    fn image(bytes: SecretBytes) -> Self {
        Self {
            body: HistoryBody::Image(bytes),
            kind: format::FormatKind::Image,
            cards: Vec::new(),
            scan: None,
            table: None,
            images: None,
        }
    }

    fn forget_derived(&mut self) {
        for (_, card) in &mut self.cards {
            card.wipe();
        }
        self.cards.clear();
        if let Some(scan) = self.scan.as_mut() {
            scan.wipe();
        }
        self.scan = None;
        if let Some(table) = self.table.as_mut() {
            table.forget_frames();
        }
        if let Some(images) = self.images.as_mut() {
            images.forget_pictures();
        }
    }
}

impl Drop for HistoryEntry {
    fn drop(&mut self) {
        match &mut self.body {
            HistoryBody::Text(text) => text.zeroize(),
            HistoryBody::Image(bytes) => bytes.zeroize(),
        }
        self.forget_derived();
    }
}

impl Drop for ClipboardImage {
    fn drop(&mut self) {
        self.rgba.zeroize();
    }
}

#[derive(Default, Clone)]
pub struct ClipboardHistory {
    entries: Vec<HistoryEntry>,
}

impl ClipboardHistory {
    /// `text` as the newest copy. Already the newest: nothing changes (`text` is zeroized), so
    /// the entry keeps its cards. Further down: that entry is replaced by a new one in front.
    pub fn record(&mut self, mut text: String) {
        let newest = self.entries.first().is_some_and(|entry| match &entry.body {
            HistoryBody::Text(existing) => existing.as_str() == text,
            HistoryBody::Image(_) => false,
        });
        if newest || text.trim().is_empty() {
            text.zeroize();
            return;
        }
        self.entries.retain(|existing| match &existing.body {
            HistoryBody::Text(existing) => existing.as_str() != text,
            HistoryBody::Image(_) => true,
        });
        self.entries.insert(0, HistoryEntry::text(text));
        self.entries.truncate(MAX_HISTORY);
    }

    /// Move entry `index` to the front without dropping it: dropping zeroizes the entry, and a
    /// picture's bytes are shared with the handles that point at it.
    fn move_to_front(&mut self, index: usize) {
        if index > 0 {
            let entry = self.entries.remove(index);
            self.entries.insert(0, entry);
        }
    }

    /// [`record`](Self::record) `text`, and say where the entry that was at `cursor` is now:
    /// one further down, or at the front when it was `text` itself. `None` when nothing was
    /// recorded (blank text), so `cursor` still holds.
    pub fn record_tracking(&mut self, text: String, cursor: usize) -> Option<usize> {
        if text.trim().is_empty() {
            let mut text = text;
            text.zeroize();
            return None;
        }
        let same = self.entries.iter().position(|entry| match &entry.body {
            HistoryBody::Text(existing) => existing.as_str() == text,
            HistoryBody::Image(_) => false,
        });
        self.record(text);
        Some(self.tracked(same, cursor))
    }

    /// Like [`record_tracking`](Self::record_tracking), for an image: the entry shares `bytes`'
    /// allocation, as a copied image's does.
    pub fn record_image_tracking(&mut self, bytes: SecretBytes, cursor: usize) -> usize {
        let same = self.entries.iter().position(|entry| match &entry.body {
            HistoryBody::Image(existing) => existing == &bytes,
            HistoryBody::Text(_) => false,
        });
        self.insert_image(bytes);
        self.tracked(same, cursor)
    }

    /// Where the entry that was at `cursor` is after an entry was put in front, `same` being
    /// where an equal entry was before (it was taken out).
    fn tracked(&self, same: Option<usize>, cursor: usize) -> usize {
        let moved = match same {
            Some(index) if index == cursor => 0,
            Some(index) if index < cursor => cursor,
            _ => cursor + 1,
        };
        moved.min(self.entries.len().saturating_sub(1))
    }

    /// The picture as the newest copy, and the handle history keeps for it.
    pub fn record_image(&mut self, bytes: Vec<u8>) -> Option<SecretBytes> {
        let bytes = SecretBytes::new(bytes)?;
        Some(self.insert_image(bytes))
    }

    /// Like [`record`](Self::record) for a picture. The entry that holds these very bytes (a
    /// history entry put back) moves to the front: dropping it would zeroize the bytes it shares
    /// with `bytes`. An equal picture in other bytes is replaced by `bytes`, as before.
    fn insert_image(&mut self, bytes: SecretBytes) -> SecretBytes {
        let shared = self.entries.iter().position(|entry| match &entry.body {
            HistoryBody::Image(existing) => existing.same_allocation(&bytes),
            HistoryBody::Text(_) => false,
        });
        if let Some(index) = shared {
            self.move_to_front(index);
            return bytes;
        }
        self.entries.retain(|existing| match &existing.body {
            HistoryBody::Image(existing) => existing != &bytes,
            HistoryBody::Text(_) => true,
        });
        self.entries.insert(0, HistoryEntry::image(bytes.clone()));
        self.entries.truncate(MAX_HISTORY);
        bytes
    }

    pub fn get(&self, index: usize) -> Option<&str> {
        let entry = self.entries.get(index)?;
        match &entry.body {
            HistoryBody::Text(text) => Some(text.as_str()),
            HistoryBody::Image(_) => None,
        }
    }

    pub fn image(&self, index: usize) -> Option<SecretBytes> {
        let entry = self.entries.get(index)?;
        match &entry.body {
            HistoryBody::Image(bytes) => Some(bytes.clone()),
            HistoryBody::Text(_) => None,
        }
    }

    pub fn mark(&self, index: usize) -> Option<&'static str> {
        Some(self.entries.get(index)?.kind.menu_symbol())
    }

    /// Where the text entry `text` is, looking at `hint` (the history cursor) first.
    pub fn text_index(&self, text: &str, hint: usize) -> Option<usize> {
        let is_text = |entry: &HistoryEntry| match &entry.body {
            HistoryBody::Text(existing) => existing.as_str() == text,
            HistoryBody::Image(_) => false,
        };
        if self.entries.get(hint).is_some_and(is_text) {
            return Some(hint);
        }
        self.entries.iter().position(is_text)
    }

    /// The card built earlier for the entry at `index` in `view` ([`remember_card`](Self::remember_card)).
    pub fn card(&self, index: usize, view: CardView) -> Option<&WorkCard> {
        self.entries
            .get(index)?
            .cards
            .iter()
            .find(|(shown, _)| *shown == view)
            .map(|(_, card)| card)
    }

    /// Keep `card` (the preview card of the text entry at `index` in `view`) with that entry.
    /// Image entries keep none: their card follows the scan, which arrives later.
    pub fn remember_card(&mut self, index: usize, view: CardView, mut card: WorkCard) {
        let Some(entry) = self.entries.get_mut(index) else {
            card.wipe();
            return;
        };
        if !matches!(entry.body, HistoryBody::Text(_)) {
            card.wipe();
            return;
        }
        if let Some(slot) = entry.cards.iter_mut().find(|(shown, _)| *shown == view) {
            slot.1.wipe();
            slot.1 = card;
        } else {
            entry.cards.push((view, card));
        }
        self.forget_derived_beyond(index);
    }

    /// The versions of the table in the text entry at `index`, if the card worked on it.
    pub fn table(&self, index: usize) -> Option<&TableVersions> {
        self.entries.get(index)?.table.as_ref()
    }

    /// The versions of the table in the text entry at `index`, made when needed. `None` for a
    /// picture. Entries further than [`DERIVED_NEAR`] from it forget their frames.
    pub fn table_mut(&mut self, index: usize) -> Option<&mut TableVersions> {
        if !matches!(self.entries.get(index)?.body, HistoryBody::Text(_)) {
            return None;
        }
        self.forget_derived_beyond(index);
        self.table_mut_in_place(index)
    }

    /// [`table_mut`](Self::table_mut) for the table window: the other entries keep what they
    /// have (the card's entry its frames), so the window and the card do not take turns
    /// working their tables out again.
    pub fn table_mut_in_place(&mut self, index: usize) -> Option<&mut TableVersions> {
        if !matches!(self.entries.get(index)?.body, HistoryBody::Text(_)) {
            return None;
        }
        Some(
            self.entries[index]
                .table
                .get_or_insert_with(crate::settings::preferred_table),
        )
    }

    /// The table whose newest job is `generation` ([`TableVersions::awaits`]).
    pub fn table_awaiting(&mut self, generation: u64) -> Option<&mut TableVersions> {
        self.entries
            .iter_mut()
            .filter_map(|entry| entry.table.as_mut())
            .find(|table| table.awaits(generation))
    }

    /// The versions of the picture entry holding these very bytes, made when needed. Entries
    /// further than [`DERIVED_NEAR`] from it forget their derived data.
    pub fn image_versions_mut(&mut self, bytes: &SecretBytes) -> Option<&mut ImageVersions> {
        let index = self.image_entry(bytes)?;
        self.forget_derived_beyond(index);
        Some(
            self.entries[index]
                .images
                .get_or_insert_with(ImageVersions::default),
        )
    }

    /// History holds the picture with these very bytes.
    pub fn holds_image(&self, bytes: &SecretBytes) -> bool {
        self.image_entry(bytes).is_some()
    }

    /// Keep `scan` with the picture version `picture` ([`ImageVersions::remember_scan`]).
    pub fn remember_version_scan(&mut self, picture: &SecretBytes, scan: &ImageScan) -> bool {
        self.entries
            .iter_mut()
            .filter_map(|entry| entry.images.as_mut())
            .any(|images| images.remember_scan(picture, scan))
    }

    /// The picture whose newest job is `generation` ([`ImageVersions::awaits`]).
    pub fn image_awaiting(&mut self, generation: u64) -> Option<&mut ImageVersions> {
        self.entries
            .iter_mut()
            .filter_map(|entry| entry.images.as_mut())
            .find(|images| images.awaits(generation))
    }

    /// The scan kept with the picture entry holding these very bytes.
    pub fn image_scan(&self, bytes: &SecretBytes) -> Option<ImageScan> {
        self.image_entry(bytes)
            .and_then(|index| self.entries[index].scan.clone())
    }

    /// Keep `scan` with the picture entry holding these very bytes.
    pub fn remember_image_scan(&mut self, bytes: &SecretBytes, scan: &ImageScan) {
        let Some(index) = self.image_entry(bytes) else {
            return;
        };
        if let Some(old) = self.entries[index].scan.as_mut() {
            old.wipe();
        }
        self.entries[index].scan = Some(scan.clone());
        self.forget_derived_beyond(index);
    }

    fn image_entry(&self, bytes: &SecretBytes) -> Option<usize> {
        self.entries.iter().position(|entry| match &entry.body {
            HistoryBody::Image(existing) => existing.same_allocation(bytes),
            HistoryBody::Text(_) => false,
        })
    }

    /// Zeroize the cards and scans of entries more than [`DERIVED_NEAR`] away from `index`.
    fn forget_derived_beyond(&mut self, index: usize) {
        for (at, entry) in self.entries.iter_mut().enumerate() {
            if at.abs_diff(index) > DERIVED_NEAR {
                entry.forget_derived();
            }
        }
    }

    pub fn byte_len(&self, index: usize) -> Option<usize> {
        let entry = self.entries.get(index)?;
        match &entry.body {
            HistoryBody::Text(text) => Some(text.len()),
            HistoryBody::Image(bytes) => Some(bytes.with(<[u8]>::len)),
        }
    }

    /// The current clipboard item stays on the Current row. Older images stay listed.
    #[cfg_attr(not(test), allow(dead_code))]
    pub fn shows_in_history(
        &self,
        index: usize,
        current_text: Option<&str>,
        current_image: Option<&SecretBytes>,
    ) -> bool {
        match self.entries.get(index).map(|entry| &entry.body) {
            Some(HistoryBody::Text(text)) => current_text != Some(text.as_str()),
            Some(HistoryBody::Image(bytes)) => {
                !current_image.is_some_and(|current| current.same_allocation(bytes))
            }
            None => false,
        }
    }

    pub fn labels(&self) -> Vec<(usize, String)> {
        self.entries
            .iter()
            .enumerate()
            .map(|(i, entry)| {
                // The format found when the entry was recorded (`one_line` would detect it again).
                (i, entry.kind.menu_symbol().to_string())
            })
            .collect()
    }

    pub fn clear(&mut self) {
        self.entries.clear();
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

/// Card title and tooltip of a copy another app marked private.
pub const HIDDEN_CONTENT: &str = "Hidden content";

/// Put `text` on the clipboard. On macOS the write carries copycraft's own pasteboard type, so
/// the poller does not take it for a new copy (see [`crate::macos_pasteboard::SELF_TYPE`]), and
/// `concealed` adds nspasteboard.org's Concealed type for other clipboard managers.
pub fn write_clipboard(text: &str, concealed: bool) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    {
        crate::macos_pasteboard::write_text(text, concealed)
    }
    #[cfg(not(target_os = "macos"))]
    {
        let _ = concealed;
        let mut cb = arboard::Clipboard::new().map_err(|e| e.to_string())?;
        cb.set_text(text.to_string()).map_err(|e| e.to_string())
    }
}

pub fn clear_clipboard() -> Result<(), String> {
    let mut cb = arboard::Clipboard::new().map_err(|e| e.to_string())?;
    cb.clear().map_err(|e| e.to_string())
}

#[cfg(not(target_os = "macos"))]
fn from_os_fallback() -> ClipboardView {
    match arboard::Clipboard::new() {
        Ok(mut cb) => {
            let text = cb.get_text().ok();
            match text {
                Some(text) if !text.trim().is_empty() => ClipboardView::Text(Zeroizing::new(text)),
                other => match cb.get_image().ok().and_then(ClipboardImage::from_arboard) {
                    Some(_) => ClipboardView::Image,
                    None if other.as_deref().is_some_and(|text| text.trim().is_empty()) => {
                        ClipboardView::Empty
                    }
                    None => ClipboardView::NoText,
                },
            }
        }
        Err(_) => ClipboardView::NoText,
    }
}

pub fn try_format_json(text: &str) -> Option<String> {
    let value: serde_json::Value = serde_json::from_str(text.trim()).ok()?;
    if !value.is_object() && !value.is_array() {
        return None;
    }
    serde_json::to_string_pretty(&value).ok()
}

pub fn formatted(text: &str) -> String {
    format::format_text(text)
}

pub fn menu_mark(text: &str) -> &'static str {
    format::detect(text).menu_symbol()
}

pub fn one_line(text: &str) -> String {
    menu_mark(text).to_string()
}

#[cfg(test)]
mod tests {
    use super::{
        ClipboardHistory, ClipboardImage, ClipboardView, SecretBytes, Zeroizing, formatted,
        one_line, try_format_json,
    };
    use zeroize::Zeroize;

    #[test]
    fn image_rejects_invalid_dimensions() {
        assert!(ClipboardImage::new(0, 1, vec![0, 0, 0, 255]).is_none());
        assert!(ClipboardImage::new(1, 1, vec![0, 0, 0]).is_none());
        assert!(ClipboardImage::new(2, 1, vec![255, 0, 0, 255]).is_none());
    }

    #[test]
    fn image_encodes_png() {
        let image = ClipboardImage::new(2, 1, vec![255, 0, 0, 255, 0, 255, 0, 255]).expect("rgba");
        let png = image.png_bytes().expect("png");
        assert!(png.starts_with(&[137, 80, 78, 71, 13, 10, 26, 10]));
        let decoded = image::load_from_memory(&png).expect("decode");
        assert_eq!(decoded.width(), 2);
        assert_eq!(decoded.height(), 1);
    }

    #[test]
    fn image_view_is_previewable() {
        let view = ClipboardView::Image;
        assert!(view.is_previewable());
        assert!(view.is_image());
        assert!(view.text().is_none());
        assert_eq!(view.label(), "img");
        assert_eq!(view.type_mark(), Some("img"));
        assert!(!ClipboardView::Empty.is_previewable());
        assert!(!ClipboardView::NoText.is_previewable());
        assert!(ClipboardView::Text(Zeroizing::new("hello".into())).is_previewable());
    }

    #[test]
    fn one_line_uses_symbol_for_plain_text() {
        assert_eq!(one_line("\n  Hello world  \nmore"), "¶");
    }

    #[test]
    fn one_line_marks_json() {
        assert_eq!(one_line("{\"name\":\"copycraft\"}"), "{}");
    }

    #[test]
    fn one_line_marks_xml() {
        assert_eq!(one_line("<root><item/></root>"), "</>");
    }

    #[test]
    fn menu_mark_hides_content() {
        let mark = super::menu_mark("Naam: Jan de Vries\nE-mailadres: jan@x.nl");
        assert_eq!(mark, "¶");
        assert!(!mark.contains("Jan"));
        assert!(!mark.contains("@"));
    }

    #[test]
    fn menu_mark_by_type() {
        assert_eq!(super::menu_mark("{\"a\":1}"), "{}");
        assert_eq!(
            super::menu_mark("name: copycraft\nitems:\n  - one\n"),
            "---"
        );
        assert_eq!(super::menu_mark("<root><item/></root>"), "</>");
        assert_eq!(super::menu_mark("https://example.com/x"), "://");
        assert_eq!(super::menu_mark("fn main() {}"), "fn");
        assert_eq!(super::menu_mark("plain"), "Aa");
        assert_eq!(super::menu_mark("name,age\nalice,30\nbob,40"), "csv");
        assert_eq!(super::menu_mark("name\tage\nalice\t30\nbob\t40"), "tsv");
    }

    #[test]
    fn formats_json_when_valid() {
        let pretty = try_format_json("{\"name\":\"copycraft\"}").expect("json");
        assert!(pretty.contains('\n'));
        assert!(pretty.contains("copycraft"));
    }

    #[test]
    fn ignores_non_json() {
        assert_eq!(try_format_json("hello"), None);
        assert_eq!(try_format_json("123"), None);
    }

    #[test]
    fn formatted_pretty_prints_json() {
        let pretty = formatted("{\"a\":1}");
        assert!(pretty.contains('\n'));
        assert!(pretty.contains('{'));
    }

    #[test]
    fn formatted_pretty_prints_xml() {
        let pretty = formatted("<a><b>x</b></a>");
        assert!(pretty.contains('\n'));
        assert!(pretty.contains("    <b>"));
    }

    #[test]
    fn one_line_is_short_symbol() {
        let label = one_line(&"a".repeat(80));
        assert_eq!(label, "Aa");
    }

    #[test]
    fn tracked_entry_moves_down_one() {
        let mut history = ClipboardHistory::default();
        history.record("old".into());
        history.record("clip".into());
        assert_eq!(history.record_tracking("dropped".into(), 0), Some(1));
        assert_eq!(history.get(0), Some("dropped"));
        assert_eq!(history.get(1), Some("clip"));
    }

    #[test]
    fn tracked_entry_that_is_the_text_moves_to_the_front() {
        let mut history = ClipboardHistory::default();
        history.record("clip".into());
        history.record("newer".into());
        assert_eq!(history.record_tracking("clip".into(), 1), Some(0));
        assert_eq!(history.get(0), Some("clip"));
        assert_eq!(history.len(), 2);
    }

    #[test]
    fn tracked_entry_keeps_its_place_when_the_text_came_from_above() {
        let mut history = ClipboardHistory::default();
        history.record("clip".into());
        history.record("dropped".into());
        history.record("newest".into());
        // "dropped" (index 1) moves to the front; "clip" stays at index 2.
        assert_eq!(history.record_tracking("dropped".into(), 2), Some(2));
        assert_eq!(history.get(2), Some("clip"));
    }

    #[test]
    fn a_tracked_image_shares_its_bytes_with_history() {
        let mut history = ClipboardHistory::default();
        history.record("clip".into());
        let bytes = SecretBytes::new(vec![1, 2, 3]).expect("bytes");
        assert_eq!(history.record_image_tracking(bytes.clone(), 0), 1);
        assert!(history.image(0).expect("image").same_allocation(&bytes));
        assert_eq!(history.get(1), Some("clip"));
        // The same picture again moves to the front instead of being listed twice.
        let again = SecretBytes::new(vec![1, 2, 3]).expect("bytes");
        assert_eq!(history.record_image_tracking(again, 1), 1);
        assert_eq!(history.len(), 2);
    }

    #[test]
    fn putting_a_history_picture_back_keeps_its_bytes() {
        let mut history = ClipboardHistory::default();
        let bytes = history.record_image(vec![1, 2, 3]).expect("image");
        history.record("newer".into());
        // Chosen from the menu: the entry's own handle goes back in front.
        let shared = history.image(1).expect("image");
        assert_eq!(history.record_image_tracking(shared, 0), 1);
        assert_eq!(history.len(), 2);
        assert!(history.image(0).expect("image").same_allocation(&bytes));
        assert_eq!(bytes.with(<[u8]>::to_vec), vec![1, 2, 3]);
    }

    #[test]
    fn recording_the_newest_text_again_changes_nothing() {
        let mut history = ClipboardHistory::default();
        history.record("older".into());
        history.record("clip".into());
        history.record("clip".into());
        assert_eq!(history.len(), 2);
        assert_eq!(history.get(0), Some("clip"));
        history.record("older".into());
        assert_eq!(history.get(0), Some("older"));
        assert_eq!(history.get(1), Some("clip"));
    }

    #[test]
    fn tracking_blank_text_records_nothing() {
        let mut history = ClipboardHistory::default();
        history.record("clip".into());
        assert_eq!(history.record_tracking("  \n".into(), 0), None);
        assert_eq!(history.len(), 1);
    }

    #[test]
    fn tracking_keeps_the_history_limit() {
        let mut history = ClipboardHistory::default();
        for i in 0..super::MAX_HISTORY {
            history.record(format!("copy {i}"));
        }
        let last = super::MAX_HISTORY - 1;
        // The tracked entry was the oldest and falls off the end.
        assert_eq!(history.record_tracking("dropped".into(), last), Some(last));
        assert_eq!(history.len(), super::MAX_HISTORY);
        assert_eq!(history.get(0), Some("dropped"));
    }

    #[test]
    fn history_dedupes_and_moves_to_front() {
        let mut history = ClipboardHistory::default();
        history.record("one".into());
        history.record("two".into());
        history.record("one".into());
        assert_eq!(history.get(0), Some("one"));
        assert_eq!(history.get(1), Some("two"));
        assert_eq!(history.labels().len(), 2);
    }

    #[test]
    fn history_keeps_an_image_after_later_text() {
        let mut history = ClipboardHistory::default();
        let image = history
            .record_image(vec![137, 80, 78, 71, 13, 10, 26, 10])
            .expect("image");
        history.record("hello".into());
        assert_eq!(history.get(0), Some("hello"));
        assert!(history.image(1).is_some());
        assert!(!history.shows_in_history(0, Some("hello"), None));
        assert!(history.shows_in_history(1, Some("hello"), None));
        assert!(!history.shows_in_history(1, None, Some(&image)));
        assert_eq!(history.mark(1), Some("img"));
        assert_eq!(history.labels()[1].1, "img");
        assert_eq!(history.byte_len(0), Some("hello".len()));
        assert_eq!(history.byte_len(1), Some(8));
        assert_eq!(history.byte_len(2), None);
    }

    #[test]
    fn history_moves_duplicate_image_to_front() {
        let mut history = ClipboardHistory::default();
        history.record_image(vec![1, 2, 3, 4]).expect("image");
        history.record("hello".into());
        history.record_image(vec![1, 2, 3, 4]).expect("image");
        assert!(history.image(0).is_some());
        assert_eq!(history.get(1), Some("hello"));
        assert_eq!(history.labels().len(), 2);
    }

    #[test]
    fn history_clear_empties_selectable_items() {
        let mut history = ClipboardHistory::default();
        history.record("one".into());
        history.record("two".into());
        history.clear();
        assert!(history.is_empty());
        assert!(history.labels().is_empty());
        assert_eq!(history.get(0), None);
    }

    #[test]
    fn clear_zeroizes_shared_image_bytes() {
        let mut history = ClipboardHistory::default();
        history.record("secret-token".into());
        let image = history
            .record_image(b"secret-bytes".to_vec())
            .expect("image");
        history.clear();
        assert!(history.is_empty());
        assert_eq!(history.get(0), None);
        assert!(image.prefix_is_zero(b"secret-bytes".len()));
    }

    #[test]
    fn zeroizing_text_overwrites_its_allocation() {
        let mut text = Zeroizing::new("secret-token".to_string());
        let ptr = text.as_ptr();
        let len = text.len();
        let cap = text.capacity();
        text.zeroize();
        assert!(text.is_empty());
        assert_eq!(text.capacity(), cap);
        // SAFETY: zeroize keeps this allocation and writes zeros across its
        // capacity. `text` still owns the buffer, and `len` is inside it.
        let wiped = unsafe { std::slice::from_raw_parts(ptr, len) };
        assert!(wiped.iter().all(|byte| *byte == 0));
    }

    fn card(excerpt: &str) -> crate::commands::WorkCard {
        crate::commands::WorkCard {
            title: "JSON".into(),
            meta: "1 B".into(),
            excerpt: excerpt.into(),
            placeholder: String::new(),
            shows_image: false,
            highlight: None,
            selectable: false,
            link_page: None,
            preview_note: None,
            error_line: None,
        }
    }

    #[test]
    fn a_remembered_card_stays_with_its_entry_and_view() {
        use crate::commands::CardView;
        let mut history = ClipboardHistory::default();
        history.record("{\"a\":1}".into());
        history.record("two".into());
        let json = history.text_index("{\"a\":1}", 0).expect("entry");
        assert_eq!(json, 1);
        assert!(history.card(json, CardView::Format).is_none());
        history.remember_card(json, CardView::Format, card("{ a }"));
        assert_eq!(
            history
                .card(json, CardView::Format)
                .map(|c| c.excerpt.as_str()),
            Some("{ a }")
        );
        assert!(history.card(json, CardView::Convert).is_none());
        assert!(history.card(0, CardView::Format).is_none());
        // Another copy in front moves the entry, and its card with it.
        history.record("three".into());
        assert!(history.card(2, CardView::Format).is_some());
        history.remember_card(2, CardView::Format, card("{ b }"));
        assert_eq!(
            history
                .card(2, CardView::Format)
                .map(|c| c.excerpt.as_str()),
            Some("{ b }")
        );
    }

    #[test]
    fn copying_an_entry_again_drops_its_card() {
        use crate::commands::CardView;
        let mut history = ClipboardHistory::default();
        history.record("one".into());
        history.remember_card(0, CardView::Original, card("one"));
        history.record("two".into());
        history.record("one".into());
        assert_eq!(history.get(0), Some("one"));
        assert!(history.card(0, CardView::Original).is_none());
    }

    #[test]
    fn evicted_and_cleared_entries_take_their_cards() {
        use crate::commands::CardView;
        let mut history = ClipboardHistory::default();
        history.record("oldest".into());
        history.remember_card(0, CardView::Original, card("oldest"));
        for i in 0..super::MAX_HISTORY - 1 {
            history.record(format!("copy {i}"));
        }
        let last = super::MAX_HISTORY - 1;
        assert!(history.card(last, CardView::Original).is_some());
        history.record("newest".into());
        assert_eq!(history.text_index("oldest", last), None);
        assert!((0..history.len()).all(|index| history.card(index, CardView::Original).is_none()));
        history.remember_card(0, CardView::Original, card("newest"));
        history.clear();
        assert!(history.card(0, CardView::Original).is_none());
    }

    #[test]
    fn only_entries_near_the_one_shown_keep_derived_data() {
        use crate::commands::{CardView, ImageScan};
        let mut history = ClipboardHistory::default();
        let image = history.record_image(vec![9, 9]).expect("image");
        for text in ["a", "b", "c", "d"] {
            history.record(text.into());
        }
        // d c b a image
        let scan = ImageScan {
            info: "PNG".into(),
            data_url: None,
            ocr: Some("text".into()),
            qr: None,
        };
        history.remember_image_scan(&image, &scan);
        assert_eq!(history.image_scan(&image), Some(scan));
        history.remember_card(3, CardView::Original, card("a"));
        assert!(history.image_scan(&image).is_some());
        history.remember_card(0, CardView::Original, card("d"));
        assert!(history.image_scan(&image).is_none());
        assert!(history.card(3, CardView::Original).is_none());
        history.remember_card(1, CardView::Original, card("c"));
        assert!(history.card(0, CardView::Original).is_some());
        assert!(history.card(1, CardView::Original).is_some());
    }

    #[test]
    fn table_versions_stay_with_their_entry_and_far_ones_forget_frames() {
        use crate::table::TableOp;
        use std::sync::atomic::AtomicBool;
        let mut history = ClipboardHistory::default();
        let table = "name,n\na,1\na,1";
        for text in [table, "b", "c", "d"] {
            history.record(text.into());
        }
        // d c b table
        let versions = history.table_mut(3).expect("text entry");
        let job = versions.push(TableOp::Dedupe, table).expect("push");
        let done = job.run(&AtomicBool::new(false)).expect("job");
        assert!(versions.finish(done));
        assert_eq!(history.table(3).map(|t| t.len()), Some(2));
        assert!(history.table(3).and_then(|t| t.frame()).is_some());
        // Showing an entry far away: the frames go, the steps stay.
        history.remember_card(0, crate::commands::CardView::Original, card("d"));
        let versions = history.table(3).expect("versions");
        assert!(versions.frame().is_none());
        assert_eq!((versions.len(), versions.cursor()), (2, 1));
        assert!(history.table(0).is_none());
        // Moving it to the front keeps them.
        history.move_to_front(3);
        assert_eq!(history.table(0).map(|t| t.len()), Some(2));
        history.clear();
        assert!(history.table(0).is_none());
    }

    #[test]
    fn a_finished_job_finds_the_table_it_was_made_for() {
        use crate::table::TableOp;
        let mut history = ClipboardHistory::default();
        for text in ["x,y\n1,2", "p,q\n3,4"] {
            history.record(text.into());
        }
        let first = history
            .table_mut(0)
            .expect("text")
            .push(TableOp::Dedupe, "p,q\n3,4")
            .expect("push");
        let second = history
            .table_mut(1)
            .expect("text")
            .push(TableOp::Dedupe, "x,y\n1,2")
            .expect("push");
        assert_ne!(first.generation, second.generation);
        assert!(history.table_awaiting(second.generation).is_some());
        assert!(history.table_awaiting(first.generation).is_some());
        assert!(history.table_awaiting(u64::MAX).is_none());
        history.clear();
        assert!(history.table_awaiting(second.generation).is_none());
    }

    #[test]
    fn pictures_have_no_table_versions() {
        let mut history = ClipboardHistory::default();
        history.record_image(vec![1, 2, 3]).expect("image");
        assert!(history.table_mut(0).is_none());
    }

    #[test]
    fn image_entries_keep_no_card() {
        use crate::commands::CardView;
        let mut history = ClipboardHistory::default();
        history.record_image(vec![1, 2, 3]).expect("image");
        history.remember_card(0, CardView::Original, card("x"));
        assert!(history.card(0, CardView::Original).is_none());
        assert_eq!(history.text_index("x", 0), None);
    }

    #[test]
    fn marks_come_from_the_format_found_on_record() {
        let mut history = ClipboardHistory::default();
        for text in [
            "{\"a\":1}",
            "fn main() {}",
            "plain",
            "name,age\nalice,30\nbob,40",
        ] {
            history.record(text.into());
            assert_eq!(history.mark(0), Some(super::menu_mark(text)));
            assert_eq!(history.labels()[0].1, super::one_line(text));
        }
        history.record_image(vec![1]).expect("image");
        assert_eq!(
            history.mark(0),
            Some(crate::format::FormatKind::Image.menu_symbol())
        );
    }

    #[test]
    fn a_wiped_card_holds_no_text() {
        let mut shown = card("secret");
        shown.link_page = Some("https://example.com/secret".into());
        shown.preview_note = Some("Showing 1 of 2".into());
        shown.wipe();
        assert!(shown.title.is_empty() && shown.meta.is_empty() && shown.excerpt.is_empty());
        assert_eq!(shown.link_page.as_deref(), Some(""));
        assert_eq!(shown.preview_note.as_deref(), Some(""));
    }
}
