// PasteProbe.swift: watch what macOS pasteboard privacy does with the NSPasteboard calls
// copycraft makes. Logs every call before and after, with its duration, so an alert that
// blocks a call shows up as "blocked" on exactly that call.
//
// Run from Terminal:   swift PasteProbe.swift [options]
// Build an app bundle: ./build_app.sh   (see README.md)
//
// Options
//   --no-read          poll, but never read contents: only changeCount, types and detect calls
//   --no-detect        skip detectedPatterns / detectedMetadata
//   --detect-values    also call detectedValues(for: [.probableWebURL, .links]); Apple documents
//                      that this one reads, and so can alert, when it finds a match
//   --interval S       poll interval in seconds (default 1.0; copycraft: 1.0 closed, 0.4 open)
//   --window           show a window (Dock icon) with a main menu Edit > Paste (Cmd-V), a custom
//                      button and a text field, to compare paste-related and other user input
//   --once             take one snapshot (with read unless --no-read), then quit
//   --show             log the first 60 characters of the text read (by default: length only)
//   --read-concealed   also read copies marked org.nspasteboard.ConcealedType (default: skip, as
//                      copycraft does)
//   --write-plain      put a test string on the general pasteboard, then quit
//   --write-concealed  same, plus org.nspasteboard.ConcealedType, then quit
//
// Inputs while running
//   Ctrl-Opt-Cmd-P     global hotkey (Carbon RegisterEventHotKey, as copycraft's global-hotkey
//                      crate): reads the pasteboard inside the hotkey handler
//   status item "PB"   left click: read (as copycraft's card under the icon)
//                      right click: menu (custom item, an item with the paste: action, ...)
//
// Log: stdout and ~/Library/Logs/PasteProbe.log. Copied text is not logged unless --show.

import AppKit
import Carbon
import UniformTypeIdentifiers

let args = CommandLine.arguments
func flag(_ name: String) -> Bool { args.contains(name) }
func option(_ name: String) -> String? {
    guard let i = args.firstIndex(of: name), i + 1 < args.count else { return nil }
    return args[i + 1]
}

let readOnChange = !flag("--no-read")
let runDetect = !flag("--no-detect")
let pollInterval = Double(option("--interval") ?? "") ?? 1.0
let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

// MARK: - Logging

let logURL = FileManager.default.homeDirectoryForCurrentUser
    .appendingPathComponent("Library/Logs/PasteProbe.log")
let stampFormat: DateFormatter = {
    let f = DateFormatter()
    f.dateFormat = "HH:mm:ss.SSS"
    return f
}()

/// Every line carries the process id, so two probes running at once are told apart.
let pidTag = "[pid \(ProcessInfo.processInfo.processIdentifier)]"

func plog(_ message: String) {
    let line = "\(stampFormat.string(from: Date())) \(pidTag) \(message)"
    print(line)
    fflush(stdout)
    if let data = (line + "\n").data(using: .utf8) {
        if let handle = try? FileHandle(forWritingTo: logURL) {
            handle.seekToEndOfFile()
            handle.write(data)
            try? handle.close()
        } else {
            try? data.write(to: logURL)
        }
    }
}

/// Runs `body`, logging the call before and after. A call that takes long most likely sat
/// behind the system's pasteboard alert (it is modal and blocks the calling thread).
@discardableResult
func timed<T>(_ label: String, _ body: () -> T) -> T {
    plog("  → \(label)")
    let start = Date()
    let value = body()
    let ms = Int(Date().timeIntervalSince(start) * 1000)
    plog("  ← \(label): \(ms) ms\(ms > 300 ? "   ⚠️ BLOCKED, probably behind an alert" : "")")
    return value
}

func behaviorName() -> String {
    if #available(macOS 15.4, *) {
        let behavior = NSPasteboard.general.accessBehavior
        switch behavior {
        case .default: return "default (0)"
        case .ask: return "ask (1)"
        case .alwaysAllow: return "alwaysAllow (2)"
        case .alwaysDeny: return "alwaysDeny (3)"
        @unknown default: return "unknown (\(behavior.rawValue))"
        }
    }
    return "n/a (macOS < 15.4)"
}

// MARK: - Detect APIs (macOS 15.4+)

@available(macOS 15.4, *)
func patternTable() -> [(PartialKeyPath<NSPasteboard.DetectedValues>, String)] {
    [
        (\NSPasteboard.DetectedValues.probableWebURL, "probableWebURL"),
        (\NSPasteboard.DetectedValues.probableWebSearch, "probableWebSearch"),
        (\NSPasteboard.DetectedValues.number, "number"),
        (\NSPasteboard.DetectedValues.links, "links"),
        (\NSPasteboard.DetectedValues.emailAddresses, "emailAddresses"),
        (\NSPasteboard.DetectedValues.phoneNumbers, "phoneNumbers"),
        (\NSPasteboard.DetectedValues.postalAddresses, "postalAddresses"),
        (\NSPasteboard.DetectedValues.calendarEvents, "calendarEvents"),
        (\NSPasteboard.DetectedValues.moneyAmounts, "moneyAmounts"),
        (\NSPasteboard.DetectedValues.flightNumbers, "flightNumbers"),
        (\NSPasteboard.DetectedValues.shipmentTrackingNumbers, "shipmentTrackingNumbers"),
    ]
}

@available(macOS 15.4, *)
func detect() async {
    let pasteboard = NSPasteboard.general
    let table = patternTable()
    let keys = Set(table.map { $0.0 })
    plog("  → detectedPatterns(for: all \(table.count) patterns)")
    var start = Date()
    do {
        let found = try await pasteboard.detectedPatterns(for: keys)
        let names = table.filter { found.contains($0.0) }.map { $0.1 }
        plog("  ← detectedPatterns: \(ms(since: start)) ms, found: \(names.isEmpty ? "-" : names.joined(separator: ", "))")
    } catch {
        plog("  ← detectedPatterns: \(ms(since: start)) ms, error: \(error)")
    }
    plog("  → detectedMetadata(for: [contentType])")
    start = Date()
    do {
        let metadata = try await pasteboard.detectedMetadata(for: [\NSPasteboard.DetectedMetadata.contentType])
        plog("  ← detectedMetadata: \(ms(since: start)) ms, contentType: \(String(describing: metadata.contentType))")
    } catch {
        plog("  ← detectedMetadata: \(ms(since: start)) ms, error: \(error)")
    }
    if flag("--detect-values") {
        plog("  → detectedValues(for: [probableWebURL, links])   (documented: reads on a match)")
        start = Date()
        do {
            let values = try await pasteboard.detectedValues(for: [
                \NSPasteboard.DetectedValues.probableWebURL, \NSPasteboard.DetectedValues.links,
            ])
            let shown = flag("--show") ? ": \(String(describing: values).prefix(200))" : " (values not logged without --show)"
            plog("  ← detectedValues: \(ms(since: start)) ms, returned\(shown)")
        } catch {
            plog("  ← detectedValues: \(ms(since: start)) ms, error: \(error)")
        }
    }
}

func ms(since start: Date) -> Int { Int(Date().timeIntervalSince(start) * 1000) }

// MARK: - Snapshot: the calls copycraft makes, in its order

/// Type checks only: changeCount, types, availableType(from:), pasteboardItems.count,
/// NSImage.canInit(with:). Returns whether the copy is marked private.
func inspectTypes() -> Bool {
    let pasteboard = NSPasteboard.general
    let types = timed("types") { pasteboard.types ?? [] }
    plog("     types: \(types.map(\.rawValue).joined(separator: ", "))")
    let hasString = timed("availableType(from: [.string])") { pasteboard.availableType(from: [.string]) != nil }
    let items = timed("pasteboardItems?.count") { pasteboard.pasteboardItems?.count ?? 0 }
    let canImage = timed("NSImage.canInit(with:)") { NSImage.canInit(with: pasteboard) }
    let marked = types.contains(concealedType) || types.contains(transientType) || types.contains(autoGeneratedType)
    plog("     string available: \(hasString), items: \(items), image: \(canImage), concealed/transient/autogenerated: \(marked)")
    return marked
}

/// Content reads: stringForType (as copycraft's read_view) and, for a picture, dataForType.
func readContents(reason: String, marked: Bool) {
    let pasteboard = NSPasteboard.general
    if marked && !flag("--read-concealed") {
        plog("     private copy: not read (as copycraft)")
        return
    }
    let text = timed("string(forType: .string)   [\(reason)]") { pasteboard.string(forType: .string) }
    if let text {
        let preview = flag("--show") ? " \"\(text.prefix(60))\"" : ""
        plog("     text: \(text.count) characters\(preview)")
    } else {
        plog("     text: nil (nothing there, or access denied)")
    }
    if pasteboard.availableType(from: [.png, .tiff]) != nil {
        let data = timed("data(forType: .png / .tiff)") {
            pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff)
        }
        plog("     image data: \(data.map { "\($0.count) bytes" } ?? "nil")")
    }
    plog("     accessBehavior after read: \(behaviorName())")
}

var busy = false

func snapshot(reason: String, read: Bool) async {
    if busy {
        plog("[\(reason)] skipped: previous snapshot still running")
        return
    }
    busy = true
    defer { busy = false }
    let pasteboard = NSPasteboard.general
    plog("[\(reason)] changeCount=\(pasteboard.changeCount) accessBehavior=\(behaviorName())")
    let marked = inspectTypes()
    if #available(macOS 15.4, *), runDetect {
        await detect()
    }
    if read {
        readContents(reason: reason, marked: marked)
    }
}

/// A read straight inside a user event handler (hotkey, click, menu item), without awaiting
/// anything first, so the read is still inside the event that caused it.
func readInsideEvent(_ reason: String) {
    plog("[\(reason)] changeCount=\(NSPasteboard.general.changeCount) accessBehavior=\(behaviorName())")
    let marked = inspectTypes()
    readContents(reason: reason, marked: marked)
}

// MARK: - Write modes (run from Terminal: a different process than the probe app)

if flag("--write-plain") || flag("--write-concealed") {
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    let text = "pasteprobe-test-\(Int(Date().timeIntervalSince1970))"
    pasteboard.setString(text, forType: .string)
    if flag("--write-concealed") {
        pasteboard.setData(Data(), forType: concealedType)
    }
    print("\(pidTag) wrote \"\(text)\"\(flag("--write-concealed") ? " + org.nspasteboard.ConcealedType" : ""), changeCount \(pasteboard.changeCount)")
    exit(0)
}

// MARK: - Global hotkey (Carbon, as the global-hotkey crate)

var hotKeyRef: EventHotKeyRef?

func registerHotKey() {
    var spec = EventTypeSpec(eventClass: OSType(kEventClassKeyboard), eventKind: UInt32(kEventHotKeyPressed))
    let installed = InstallEventHandler(GetApplicationEventTarget(), { _, _, _ -> OSStatus in
        readInsideEvent("hotkey ⌃⌥⌘P (inside handler)")
        return OSStatus(noErr)
    }, 1, &spec, nil, nil)
    let id = EventHotKeyID(signature: OSType(0x5050_5242), id: 1)
    let registered = RegisterEventHotKey(UInt32(kVK_ANSI_P), UInt32(cmdKey | optionKey | controlKey), id,
                                         GetApplicationEventTarget(), 0, &hotKeyRef)
    plog("hotkey ⌃⌥⌘P: InstallEventHandler \(installed), RegisterEventHotKey \(registered)")
}

// MARK: - App

/// First responder of the window, so Edit > Paste (⌘V) in the main menu reaches paste(_:).
final class ProbeView: NSView {
    override var acceptsFirstResponder: Bool { true }
    @objc func paste(_ sender: Any?) {
        readInsideEvent("main menu Edit > Paste / ⌘V (paste: action)")
    }
}

final class AppDelegate: NSObject, NSApplicationDelegate {
    var statusItem: NSStatusItem!
    var menu = NSMenu()
    var window: NSWindow?
    var timer: Timer?
    var lastChange = NSPasteboard.general.changeCount

    func applicationDidFinishLaunching(_ notification: Notification) {
        let info = ProcessInfo.processInfo
        plog("==== PasteProbe start, macOS \(info.operatingSystemVersionString)")
        plog("bundle id: \(Bundle.main.bundleIdentifier ?? "(none: not an app bundle)")  path: \(Bundle.main.bundlePath)")
        let preview = UserDefaults.standard.object(forKey: "EnablePasteboardPrivacyDeveloperPreview")
        plog("EnablePasteboardPrivacyDeveloperPreview (this process' defaults): \(preview.map { "\($0)" } ?? "not set")")
        plog("accessBehavior: \(behaviorName())")
        plog("options: read=\(readOnChange) detect=\(runDetect) interval=\(pollInterval)s")
        logSignature()

        if flag("--once") {
            Task { @MainActor in
                await snapshot(reason: "once", read: readOnChange)
                NSApp.terminate(nil)
            }
            return
        }

        setUpStatusItem()
        registerHotKey()
        if flag("--window") { setUpWindow() }
        timer = Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        plog("polling changeCount every \(pollInterval) s; copy something in another app")
    }

    func logSignature() {
        guard Bundle.main.bundleIdentifier != nil else { return }
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/codesign")
        process.arguments = ["-dv", Bundle.main.bundlePath]
        let pipe = Pipe()
        process.standardError = pipe
        process.standardOutput = pipe
        do {
            try process.run()
            process.waitUntilExit()
            let out = String(data: pipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8) ?? ""
            for line in out.split(separator: "\n")
            where line.hasPrefix("Identifier") || line.hasPrefix("CDHash") || line.hasPrefix("TeamIdentifier")
                || line.hasPrefix("Signature") || line.hasPrefix("Authority") {
                plog("codesign: \(line)")
            }
        } catch {
            plog("codesign: \(error)")
        }
    }

    func poll() {
        let change = NSPasteboard.general.changeCount
        guard change != lastChange else { return }
        lastChange = change
        Task { @MainActor in await snapshot(reason: "poll", read: readOnChange) }
    }

    func setUpStatusItem() {
        statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
        statusItem.button?.title = "PB"
        statusItem.button?.target = self
        statusItem.button?.action = #selector(statusClicked(_:))
        statusItem.button?.sendAction(on: [.leftMouseUp, .rightMouseUp])

        menu.addItem(withTitle: "Read now (custom menu action)", action: #selector(readFromMenu(_:)), keyEquivalent: "").target = self
        menu.addItem(withTitle: "Paste (paste: action)", action: #selector(paste(_:)), keyEquivalent: "").target = self
        menu.addItem(withTitle: "Detect only (no read)", action: #selector(detectOnly(_:)), keyEquivalent: "").target = self
        menu.addItem(.separator())
        menu.addItem(withTitle: "Open Privacy & Security › Paste from Other Apps", action: #selector(openSettings(_:)), keyEquivalent: "").target = self
        menu.addItem(withTitle: "Log accessBehavior", action: #selector(logBehavior(_:)), keyEquivalent: "").target = self
        menu.addItem(.separator())
        menu.addItem(withTitle: "Quit", action: #selector(NSApplication.terminate(_:)), keyEquivalent: "q")
    }

    @objc func statusClicked(_ sender: Any?) {
        if NSApp.currentEvent?.type == .rightMouseUp {
            statusItem.menu = menu
            statusItem.button?.performClick(nil)
            statusItem.menu = nil
        } else {
            readInsideEvent("status item left click (inside action)")
        }
    }

    @objc func readFromMenu(_ sender: Any?) { readInsideEvent("status menu: custom item") }
    @objc func paste(_ sender: Any?) { readInsideEvent("status menu: item with paste: action") }
    @objc func detectOnly(_ sender: Any?) {
        Task { @MainActor in await snapshot(reason: "status menu: detect only", read: false) }
    }
    @objc func logBehavior(_ sender: Any?) { plog("accessBehavior: \(behaviorName())") }
    @objc func openSettings(_ sender: Any?) {
        // macOS 26 path (reported on mjtsai.com); the 15.x path was
        // x-apple.systempreferences:com.apple.preference.security?Privacy_Pasteboard
        let url = URL(string: "x-apple.systempreferences:com.apple.settings.PrivacySecurity.extension?Privacy_Pasteboard")!
        NSWorkspace.shared.open(url)
    }
    @objc func readFromButton(_ sender: Any?) { readInsideEvent("window: custom NSButton") }

    func setUpWindow() {
        let mainMenu = NSMenu()
        let appItem = NSMenuItem()
        appItem.submenu = NSMenu()
        appItem.submenu?.addItem(withTitle: "Quit PasteProbe", action: #selector(NSApplication.terminate(_:)), keyEquivalent: "q")
        mainMenu.addItem(appItem)
        let editItem = NSMenuItem()
        let edit = NSMenu(title: "Edit")
        edit.addItem(withTitle: "Paste", action: #selector(ProbeView.paste(_:)), keyEquivalent: "v")
        editItem.submenu = edit
        mainMenu.addItem(editItem)
        NSApp.mainMenu = mainMenu

        let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 460, height: 170),
                              styleMask: [.titled, .closable], backing: .buffered, defer: false)
        window.title = "PasteProbe"
        let view = ProbeView(frame: window.contentRect(forFrameRect: window.frame))
        let label = NSTextField(wrappingLabelWithString:
            "Click here, then ⌘V or Edit > Paste: read in paste: (paste-related).\nThe button reads in a custom action. The text field pastes the normal way (control).")
        label.frame = NSRect(x: 16, y: 100, width: 428, height: 56)
        let button = NSButton(title: "Read (custom button)", target: self, action: #selector(readFromButton(_:)))
        button.frame = NSRect(x: 16, y: 60, width: 200, height: 30)
        let field = NSTextField(frame: NSRect(x: 16, y: 20, width: 428, height: 24))
        field.placeholderString = "text field: paste here with ⌘V (system paste, control)"
        [label, button, field].forEach { view.addSubview($0) }
        window.contentView = view
        window.center()
        window.makeKeyAndOrderFront(nil)
        window.makeFirstResponder(view)
        NSApp.activate(ignoringOtherApps: true)
        self.window = window
    }
}

let app = NSApplication.shared
let delegate = AppDelegate()
app.delegate = delegate
app.setActivationPolicy(flag("--window") ? .regular : .accessory)
app.run()
